### ISSUE TITLE
Failed to import transformers.trainer because of the following error 

### ISSUE THREAD

**Issue by yangp725** [project-baize/baize-chatbot#24]
Have u encountered the following error? And what's ur torch/transformers/peft vesion?

<img width="694" alt="image" src="https://user-images.githubusercontent.com/13365326/230571789-e1fda080-41b9-492f-a2e5-89d19bf4da75.png">

> RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
No module named 'torch._six'

**Comment by JetRunner** [comment]
Please upgrade your `torch` to the latest version.
