### ISSUE TITLE
Performance cannot align with demo

### ISSUE THREAD

**Issue by LIO-H-ZEN** [project-baize/baize-chatbot#28]
base_model=decapoda-research/llama-7b-hf
lora_model=project-baize/baize-lora-7B
python app.py $base_model $lora_model

same Top_p, Temperature

even 13b performs poor

**Comment by guoday** [comment]
Which two models did you compare?

**Comment by JetRunner** [comment]
The code used by the online demo is here: https://huggingface.co/spaces/project-baize/Baize-7B/blob/main/app.py
Which is exactly the same as local demo. Can you provide more details?

**Comment by LIO-H-ZEN** [comment]
I overlooked the randomness, my fault... I turn the Temperature to 0.1 and the Top_p to 1.0. This time the local result is exactly the same as the online result. 
Besides, as 13B seems similar to 7B, i try to test 30B, but encounter this problem: https://github.com/project-baize/baize-chatbot/issues/31
