### ISSUE TITLE
30B failed, pytorch_model-00039-of-00061.bin, If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by LIO-H-ZEN** [project-baize/baize-chatbot#31]
OSError: Unable to load weights from pytorch checkpoint file for 'model_cache/models--decapoda-research--llama-30b-hf/snapshots/f991780f9362b2fcaefad066cd235058844562b7/pytorch_model-00039-of-00061.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

The other shard is fine, any suggestion?

**Comment by JetRunner** [comment]
This seems to be a problem of the base model instead of Baize. Maybe one shard file is damaged. You can try to clear the cache and redownload the files.
